# ~/.config/starship.toml

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = true

# format = """$character"""
right_format = """
$python\
$nodejs\
$lua\
$cmd_duration 
"""

format = """
$hostname\
$directory\
$git_branch\
$git_status
$username\
$character
"""

[username]
format = '[󰀉 $user]($style) '
#show_always = true
style = 'bright-green'

[hostname]
ssh_only = false
format = '[󰛳 $hostname$ssh_symbol]($style) '
ssh_symbol = ' 󰌘 '
style = 'bright-cyan'

[directory]
truncation_length = 5
truncate_to_repo = false
before_repo_root_style = 'blue'
style = 'bold blue'
repo_root_style = 'underline bold blue'
repo_root_format = '[󰉋 $before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
truncation_symbol = '…/'
read_only = '  Read Only '
format = '[󱂵 $path]($style)[$read_only]($read_only_style) '

[cmd_duration]
min_time = 500
format = '[ $duration]($style) '
style = 'fg:8'

[git_branch]
#ignore_branches = ['master', 'main']
style = 'bold italic fg:8'
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ' '

[git_status]
style = 'italic fg:8'
format = '([\[$ahead_behind\]]($style) )'
ahead = '⇡${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[nodejs]
format = '[$symbol($version )]($style) '
symbol = ' '
#style = 'fg:172'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '
symbol = ' '
#style = 'fg:172'

[lua]
format = '[$symbol($version )]($style) '
symbol = ' '
#style = 'fg:172'
